name: "Build PR"

on:
  pull_request:
    branches:
      - staging
      - production

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Node Dependencies
        run: npm ci

      - name: Run Test
        run: npm run test

      - name: App Build
        run: npm run build
